### ISSUE TITLE
wtf

### ISSUE THREAD

**Issue by fireanmeng** [wrj2009/BuaiXueOS#1]
有几个点比较离谱
第一是
book我初看以为是把每本书new一个 点进去一看 怎么继承的activity 加个后缀吧（例：BookActivity）
第二是
Main里的那个1/0不如直接改成throw new exception 没必要除个0
或者new完exception以后fillinstacktrace防止被看到堆栈跟踪（？）
又或者死锁 我个人不知道Android有类似电脑jvm上面的强制输出thread dump

**Comment by wrj2009** [comment]
感谢建议，我没学过 Java，也从来没开发过 Android 应用，本来也没打算把它做得很完美（[https://www.bilibili.com/video/BV1wT411G7Ya](https://www.bilibili.com/video/BV1wT411G7Ya)）

我待会儿去 README 和仓库介绍里面加个提示

**Comment by fireanmeng** [comment]
> 感谢建议，我没学过 Java，也从来没开发过 Android 应用，本来也没打算把它做得很完美（[https://www.bilibili.com/video/BV1wT411G7Ya）](https://www.bilibili.com/video/BV1wT411G7Ya%EF%BC%89)
> 
> 我待会儿去 README 和仓库介绍里面加个提示

虽然但是 视频没了
